services:
  # API Service
  - type: web
    name: fraud-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: fraud-detection-db
          property: connectionString

  # Dashboard Service
  - type: web
    name: fraud-detection-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && python dashboard/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: API_BASE_URL
        value: https://fraud-detection-api.onrender.com/api
      - key: PORT
        value: 8050

databases:
  - name: fraud-detection-db
    databaseName: fraud_detection
    user: fraud_detection_user
    plan: free
