name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest
        
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fdam-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: .

    - name: Deploy Dashboard to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fdam-dashboard'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_DASHBOARD_PUBLISH_PROFILE }}
        package: .
