# Add your API URL here for deployment
# For local development, this can be localhost
# For production, use your deployed API URL

API_BASE_URL = "http://localhost:8001/api"

# Example for production:
# API_BASE_URL = "https://your-api-domain.com/api"